apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.data.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secret.data.DB_PASSWORD | quote }}