apiVersion: v2
name: loki-stack
description: A wrapper chart for Grafana Loki Stack
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: loki-stack
    version: "2.10.2"
    repository: "https://grafana.github.io/helm-charts"